"""create donation requests table

Revision ID: 13d1e35bfdda
Revises: 84ea4428e87a
Create Date: 2026-09-29 00:02:32.491564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d1e35bfdda'
down_revision: Union[str, Sequence[str], None] = '84ea4428e87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_requests',
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('ngo_id', sa.UUID(), nullable=False),
    sa.Column('servings_requested', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_requests_donation_id'), 'donation_requests', ['donation_id'], unique=False)
    op.create_index(op.f('ix_donation_requests_id'), 'donation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_donation_requests_ngo_id'), 'donation_requests', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_donation_requests_status'), 'donation_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donation_requests_status'), table_name='donation_requests')
    op.drop_index(op.f('ix_donation_requests_ngo_id'), table_name='donation_requests')
    op.drop_index(op.f('ix_donation_requests_id'), table_name='donation_requests')
    op.drop_index(op.f('ix_donation_requests_donation_id'), table_name='donation_requests')
    op.drop_table('donation_requests')
    # ### end Alembic commands ###
