"""create deliveries table

Revision ID: 27a0384c863d
Revises: 13d1e35bfdda
Create Date: 2026-09-29 23:01:33.435482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a0384c863d'
down_revision: Union[str, Sequence[str], None] = '13d1e35bfdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ngo_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNMENT_PENDING', 'ACCEPTED', 'PICKED_UP', 'ON_THE_WAY', 'DELIVERED', 'CANCELLED', name='deliverystatus'), nullable=False),
    sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_image_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['delivery_partner_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['donation_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_donation_id'), 'deliveries', ['donation_id'], unique=False)
    op.create_index(op.f('ix_deliveries_driver_id'), 'deliveries', ['driver_id'], unique=False)
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_deliveries_ngo_id'), 'deliveries', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_deliveries_request_id'), 'deliveries', ['request_id'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_request_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_ngo_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_driver_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_donation_id'), table_name='deliveries')
    op.drop_table('deliveries')
    # ### end Alembic commands ###
