"""create initial user profiles and donation tables

Revision ID: 84ea4428e87a
Revises: 
Create Date: 2026-09-26 14:20:05.774412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '84ea4428e87a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('DONOR', 'NGO', 'DELIVERY_PARTNER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_geospatial_table('delivery_partner_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BICYCLE', 'MOTORBIKE', 'CAR', 'VAN', 'TRUCK', 'AUTO_RICKSHAW', name='vehicletype'), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('current_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_geospatial_index('idx_delivery_partner_profiles_current_location', 'delivery_partner_profiles', ['current_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_delivery_partner_profiles_id'), 'delivery_partner_profiles', ['id'], unique=False)
    op.create_geospatial_table('donor_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_geospatial_index('idx_donor_profiles_location', 'donor_profiles', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_donor_profiles_id'), 'donor_profiles', ['id'], unique=False)
    op.create_geospatial_table('ngo_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('capacity_meals_per_day', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_geospatial_index('idx_ngo_profiles_location', 'ngo_profiles', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_ngo_profiles_id'), 'ngo_profiles', ['id'], unique=False)
    op.create_geospatial_table('donations',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('food_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'REQUESTED', 'ACCEPTED', 'PICKED_UP', 'ON_THE_WAY', 'DELIVERED', 'CANCELLED', 'EXPIRED', name='donationstatus'), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_donations_pickup_location', 'donations', ['pickup_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_expires_at'), 'donations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    #op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_expires_at'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_geospatial_index('idx_donations_pickup_location', table_name='donations', postgresql_using='gist', column_name='pickup_location')
    op.drop_geospatial_table('donations')
    op.drop_index(op.f('ix_ngo_profiles_id'), table_name='ngo_profiles')
    op.drop_geospatial_index('idx_ngo_profiles_location', table_name='ngo_profiles', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('ngo_profiles')
    op.drop_index(op.f('ix_donor_profiles_id'), table_name='donor_profiles')
    op.drop_geospatial_index('idx_donor_profiles_location', table_name='donor_profiles', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('donor_profiles')
    op.drop_index(op.f('ix_delivery_partner_profiles_id'), table_name='delivery_partner_profiles')
    op.drop_geospatial_index('idx_delivery_partner_profiles_current_location', table_name='delivery_partner_profiles', postgresql_using='gist', column_name='current_location')
    op.drop_geospatial_table('delivery_partner_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###